
wait_for_action_finish: true
ready_state: Ready
planning_state: Planning
dispatching_state: Dispatching
start_command: plan
cancel_command: cancel
achieved_status: action achieved
failed_status: action failed
enabled_status: action enabled
