objects:
  robot: [r1, r2, r3]
#  base_station: [bs]
#  ring_station: [rs1, rs2]
#  cap_station: [cs1, cs2]
#  delivery_station: [ds]
#  s_location: [start]
#  bs_output: [bs_out]
#  rs_input: [rs1_in, rs2_in]
#  rs_output: [rs1_out, rs2_out]
#  cs_input: [cs1_in, cs2_in]
#  cs_output: [cs1_out, cs2_out]
#  ds_input: [ds_in]

init:    
  robot-at-init: [r1]
  robot-precedes: 
    - [r1, r2]
    - [r1, r3]
    - [r2, r3]
  input-location:
    - [cs1_in, cs1]
    - [cs2_in, cs2]
    - [rs1_in, rs1]
    - [rs2_in, rs2]
    - [ds_in, ds]
  output-location:
    - [cs1_out, cs1]
    - [cs2_out, cs2]
    - [rs1_out, rs1]
    - [rs2_out, rs2]
    - [bs_out, bs]
    - [bs_in, bs]
  robot-assigned-machine:
    - [r1, cs1]
    - [r1, cs2]
    - [r1, rs1]
    - [r1, rs2]
    - [r1, bs]

init_numerical:
  material-stored:
   - 
     args: [rs1]
     value: 0
   - 
     args: [rs2]
     value: 0
   - 
     args: [cs1]
     value: 0
   - 
     args: [cs2]
     value: 0
   - 
     args: [ds]
     value: 0
   - 
     args: [bs]
     value: 0
#  path-length:
#   - 
#     args: [START, bs_in]
#     value: 15.0

  #wp-on-shelf:
  #  - [cg1, C-CS1, LEFT]
  #  - [cg2, C-CS1, MIDDLE]
  #  - [cg3, C-CS1, RIGHT]
  #  - [cb1, C-CS2, LEFT]
  #  - [cb2, C-CS2, MIDDLE]
  #  - [cb3, C-CS2, RIGHT]

  # rs-ring-spec:
  #   - [C-RS1, RING_GREEN]
  #   - [C-RS1, RING_YELLOW]
  #   - [C-RS2, RING_BLUE]
  #   - [C-RS2, RING_ORANGE]

  # To run with a fixed order uncomment:
  # order-complexity:
  #   - [o1, C3]
  # order-base-color:
  #   - [o1, BASE_BLACK]
  # order-ring1-color:
  #   - [o1, RING_GREEN]
  # order-ring2-color:
  #   - [o1, RING_BLUE]
  # order-ring3-color:
  #   - [o1, RING_ORANGE]
  # order-cap-color:
  #   - [o1, CAP_GREY]

# To set a fixed goal uncomment:
#goal:
#  cap-buffered: 
#  - [cs1]
#  - [cs2]

#goal_numerical:
#  material-stored:
#   - 
#     args: [C_RS1]
#     value: 1
