objects:
  robot: [r1, r2, r3]

init:    
  robot-at-init: [r1, r2, r3]
  robot-precedes: 
    - [r1, r2]
    - [r1, r3]
    - [r2, r3]
  input-location:
    - [cs1_in, cs1]
    - [cs2_in, cs2]
    - [rs1_in, rs1]
    - [rs2_in, rs2]
    - [ds_in, ds]
  output-location:
    - [cs1_out, cs1]
    - [cs2_out, cs2]
    - [rs1_out, rs1]
    - [rs2_out, rs2]
    - [bs_out, bs]

init_numerical:
  material-stored:
   - 
     args: [rs1]
     value: 0
   - 
     args: [rs2]
     value: 0.0
#  path-length:
#   - 
#     args: [START, bs_in]
#     value: 15.0

  #wp-on-shelf:
  #  - [cg1, C-CS1, LEFT]
  #  - [cg2, C-CS1, MIDDLE]
  #  - [cg3, C-CS1, RIGHT]
  #  - [cb1, C-CS2, LEFT]
  #  - [cb2, C-CS2, MIDDLE]
  #  - [cb3, C-CS2, RIGHT]

  # rs-ring-spec:
  #   - [C-RS1, RING_GREEN]
  #   - [C-RS1, RING_YELLOW]
  #   - [C-RS2, RING_BLUE]
  #   - [C-RS2, RING_ORANGE]

  # To run with a fixed order uncomment:
  # order-complexity:
  #   - [o1, C3]
  # order-base-color:
  #   - [o1, BASE_BLACK]
  # order-ring1-color:
  #   - [o1, RING_GREEN]
  # order-ring2-color:
  #   - [o1, RING_BLUE]
  # order-ring3-color:
  #   - [o1, RING_ORANGE]
  # order-cap-color:
  #   - [o1, CAP_GREY]

# To set a fixed goal uncomment:
#goal:
#  robot-at: 
#  - [R1, START]

#goal_numerical:
#  material-stored:
#   - 
#     args: [C_RS1]
#     value: 1
