(define (problem rcll-production-steps_task)
(:domain rcll-production-steps)
(:objects
	r1 r2 r3 - robot
	p10 - product
	silver_base_p10 grey_cap_p10 gate2_delivery_p10 - step
	p70 - product
	silver_base_p70 blue_ring_p70 orange_ring_p70 yellow_ring_p70 black_cap_p70 gate2_delivery_p70 - step
)
(:init
	(add-one zero one)
	(add-one one two)
	(add-one two three)
	(subtract three zero three)
	(subtract two zero two)
	(subtract one zero one)
	(subtract zero zero zero)
	(subtract three one two)
	(subtract two one one)
	(subtract one one zero)
	(subtract three two one)
	(subtract two two zero)
	(has-step p10 silver_base_p10)
	(has-step p10 grey_cap_p10)
	(has-step p10 gate2_delivery_p10)
	(initial-step silver_base_p10)
	(has-step p70 silver_base_p70)
	(has-step p70 blue_ring_p70)
	(has-step p70 orange_ring_p70)
	(has-step p70 yellow_ring_p70)
	(has-step p70 black_cap_p70)
	(has-step p70 gate2_delivery_p70)
	(initial-step silver_base_p70)
	(input-location cs1_in cs1)
	(input-location cs2_in cs2)
	(input-location rs1_in rs1)
	(input-location rs2_in rs2)
	(input-location ds_in ds)
	(output-location cs1_out cs1)
	(output-location cs2_out cs2)
	(output-location rs1_out rs1)
	(output-location rs2_out rs2)
	(output-location bs_out bs)
	(robot-at-init r1)
	(robot-at-init r2)
	(robot-at-init r3)
	(first-robot r1)
	(robot-precedes r1 r2)
	(robot-precedes r2 r3)
	(step-at-machine silver_base_p10 bs)
	(step-at-machine grey_cap_p10 cs1)
	(step-at-machine gate2_delivery_p10 ds)
	(step-precedes silver_base_p10 grey_cap_p10)
	(step-precedes grey_cap_p10 gate2_delivery_p10)
	(step-at-machine silver_base_p70 bs)
	(step-at-machine blue_ring_p70 rs2)
	(step-at-machine orange_ring_p70 rs2)
	(step-at-machine yellow_ring_p70 rs1)
	(step-at-machine black_cap_p70 cs2)
	(step-at-machine gate2_delivery_p70 ds)
	(step-precedes silver_base_p70 blue_ring_p70)
	(step-precedes blue_ring_p70 orange_ring_p70)
	(step-precedes orange_ring_p70 yellow_ring_p70)
	(step-precedes yellow_ring_p70 black_cap_p70)
	(step-precedes black_cap_p70 gate2_delivery_p70)
	(material-required silver_base_p10 zero)
	(material-required grey_cap_p10 zero)
	(material-required gate2_delivery_p10 zero)
	(material-required blue_ring_p70 one)
	(material-required orange_ring_p70 zero)
	(material-required yellow_ring_p70 two)
	(material-required silver_base_p70 zero)
	(material-required black_cap_p70 zero)
	(material-required gate2_delivery_p70 zero)
	(material-stored rs2 zero)
	(material-stored rs1 zero)
	(material-stored cs2 zero)
	(material-stored cs1 zero)
	(material-stored ds zero)
	(material-stored bs zero)
	(= (path-length bs_in bs_out) 10)
	(= (path-length bs_in cs1_in) 56)
	(= (path-length bs_in cs1_out) 64)
	(= (path-length bs_in cs2_in) 50)
	(= (path-length bs_in cs2_out) 39)
	(= (path-length bs_in ds_in) 39)
	(= (path-length bs_in rs1_in) 19)
	(= (path-length bs_in rs1_out) 30)
	(= (path-length bs_in rs2_in) 21)
	(= (path-length bs_in rs2_out) 12)
	(= (path-length bs_out bs_in) 10)
	(= (path-length bs_out cs1_in) 62)
	(= (path-length bs_out cs1_out) 69)
	(= (path-length bs_out cs2_in) 55)
	(= (path-length bs_out cs2_out) 45)
	(= (path-length bs_out ds_in) 45)
	(= (path-length bs_out rs1_in) 24)
	(= (path-length bs_out rs1_out) 35)
	(= (path-length bs_out rs2_in) 29)
	(= (path-length bs_out rs2_out) 16)
	(= (path-length cs1_in bs_in) 56)
	(= (path-length cs1_in bs_out) 62)
	(= (path-length cs1_in cs1_out) 13)
	(= (path-length cs1_in cs2_in) 21)
	(= (path-length cs1_in cs2_out) 21)
	(= (path-length cs1_in ds_in) 27)
	(= (path-length cs1_in rs1_in) 42)
	(= (path-length cs1_in rs1_out) 31)
	(= (path-length cs1_in rs2_in) 47)
	(= (path-length cs1_in rs2_out) 58)
	(= (path-length cs1_out bs_in) 64)
	(= (path-length cs1_out bs_out) 69)
	(= (path-length cs1_out cs1_in) 13)
	(= (path-length cs1_out cs2_in) 21)
	(= (path-length cs1_out cs2_out) 29)
	(= (path-length cs1_out ds_in) 36)
	(= (path-length cs1_out rs1_in) 49)
	(= (path-length cs1_out rs1_out) 39)
	(= (path-length cs1_out rs2_in) 55)
	(= (path-length cs1_out rs2_out) 67)
	(= (path-length cs2_in bs_in) 50)
	(= (path-length cs2_in bs_out) 55)
	(= (path-length cs2_in cs1_in) 21)
	(= (path-length cs2_in cs1_out) 21)
	(= (path-length cs2_in cs2_out) 24)
	(= (path-length cs2_in ds_in) 33)
	(= (path-length cs2_in rs1_in) 35)
	(= (path-length cs2_in rs1_out) 35)
	(= (path-length cs2_in rs2_in) 51)
	(= (path-length cs2_in rs2_out) 60)
	(= (path-length cs2_out bs_in) 39)
	(= (path-length cs2_out bs_out) 45)
	(= (path-length cs2_out cs1_in) 21)
	(= (path-length cs2_out cs1_out) 29)
	(= (path-length cs2_out cs2_in) 24)
	(= (path-length cs2_out ds_in) 25)
	(= (path-length cs2_out rs1_in) 25)
	(= (path-length cs2_out rs1_out) 26)
	(= (path-length cs2_out rs2_in) 42)
	(= (path-length cs2_out rs2_out) 49)
	(= (path-length ds_in bs_in) 39)
	(= (path-length ds_in bs_out) 45)
	(= (path-length ds_in cs1_in) 27)
	(= (path-length ds_in cs1_out) 36)
	(= (path-length ds_in cs2_in) 33)
	(= (path-length ds_in cs2_out) 25)
	(= (path-length ds_in rs1_in) 25)
	(= (path-length ds_in rs1_out) 14)
	(= (path-length ds_in rs2_in) 29)
	(= (path-length ds_in rs2_out) 41)
	(= (path-length rs1_in bs_in) 19)
	(= (path-length rs1_in bs_out) 24)
	(= (path-length rs1_in cs1_in) 42)
	(= (path-length rs1_in cs1_out) 49)
	(= (path-length rs1_in cs2_in) 35)
	(= (path-length rs1_in cs2_out) 25)
	(= (path-length rs1_in ds_in) 25)
	(= (path-length rs1_in rs1_out) 26)
	(= (path-length rs1_in rs2_in) 32)
	(= (path-length rs1_in rs2_out) 29)
	(= (path-length rs1_out bs_in) 30)
	(= (path-length rs1_out bs_out) 35)
	(= (path-length rs1_out cs1_in) 31)
	(= (path-length rs1_out cs1_out) 39)
	(= (path-length rs1_out cs2_in) 35)
	(= (path-length rs1_out cs2_out) 26)
	(= (path-length rs1_out ds_in) 14)
	(= (path-length rs1_out rs1_in) 26)
	(= (path-length rs1_out rs2_in) 21)
	(= (path-length rs1_out rs2_out) 32)
	(= (path-length rs2_in bs_in) 21)
	(= (path-length rs2_in bs_out) 29)
	(= (path-length rs2_in cs1_in) 47)
	(= (path-length rs2_in cs1_out) 55)
	(= (path-length rs2_in cs2_in) 51)
	(= (path-length rs2_in cs2_out) 42)
	(= (path-length rs2_in ds_in) 29)
	(= (path-length rs2_in rs1_in) 32)
	(= (path-length rs2_in rs1_out) 21)
	(= (path-length rs2_in rs2_out) 14)
	(= (path-length rs2_out bs_in) 12)
	(= (path-length rs2_out bs_out) 16)
	(= (path-length rs2_out cs1_in) 58)
	(= (path-length rs2_out cs1_out) 67)
	(= (path-length rs2_out cs2_in) 60)
	(= (path-length rs2_out cs2_out) 49)
	(= (path-length rs2_out ds_in) 41)
	(= (path-length rs2_out rs1_in) 29)
	(= (path-length rs2_out rs1_out) 32)
	(= (path-length rs2_out rs2_in) 14)
	(= (path-length start bs_in) 7)
	(= (path-length start bs_out) 12)
	(= (path-length start cs1_in) 54)
	(= (path-length start cs1_out) 61)
	(= (path-length start cs2_in) 47)
	(= (path-length start cs2_out) 37)
	(= (path-length start ds_in) 37)
	(= (path-length start rs1_in) 17)
	(= (path-length start rs1_out) 27)
	(= (path-length start rs2_in) 27)
	(= (path-length start rs2_out) 17)
	(robot-at-init r1)
	(robot-at-init r2)
	(robot-at-init r3)
	(= (total-cost) 0)
)
(:goal (and
	(step-completed silver_base_p10)
	(step-completed grey_cap_p10)
	(step-completed gate2_delivery_p10)

	(step-completed silver_base_p70)
	(step-completed blue_ring_p70)
	(step-completed orange_ring_p70)
	(step-completed yellow_ring_p70)
	(step-completed black_cap_p70)
	(step-completed gate2_delivery_p70)

	;(cap-buffered cs1)
	;(cap-buffered cs2)
	;(robot-at r1 bs_in)
	;(robot-holding-product r1 p70)
	;(robot-holding-material r1)
	;(not (material-at cs2_out))
	;(not (material-at cs1_out))
)))
